name: Generate VIVO Ontology Files

on: workflow_dispatch 

permissions:
  contents: write

jobs:
  run-odk-seed:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Grab your empty repository
        uses: actions/checkout@v4

      - name: 2. Download the ODK instruction script
        run: wget https://raw.githubusercontent.com/INCATools/ontology-development-kit/v1.3.1/seed-via-docker.sh

      - name: 3. Give the outer Robot a name 
        run: |
          git config --global user.name "GitHub Actions Robot"
          git config --global user.email "actions@github.com"

      - name: 4. Turn on ODK (Docker) to generate files
        run: sh seed-via-docker.sh -u ${{ github.actor }} -t "VIVO Test Ontology" --gitname "GitHub Actions Robot" --gitemail "actions@github.com" vivotest

      - name: 5. Unpack the folder 
        run: |
          sudo chown -R $USER target/
          rm -rf target/vivotest/.git
          
          mv target/vivotest/.github/workflows target/vivotest/generated-workflows
          
          cp -a target/vivotest/. ./
          rm -rf target
          rm seed-via-docker.sh*
          
      - name: 6. Save the unpacked files to GitHub
        run: |
          git add .
          git commit -m "Unpacked ODK starter files"
          git push
