# Basic ODK workflow

name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  ontology_qc:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6.1
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Run ontology QC checks
        env:
          DEFAULT_BRANCH: main
        run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' test IMP=false PAT=false MIR=false

      - name: Save QC reports
        run: |
          cd src/ontology
          make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' custom_reports IMP=false PAT=false MIR=false
          cd ../..
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/ontology/reports/
          git diff --staged --quiet || git commit -m "ci: update QC reports"
          git push